name: motchi
description: Motchi is a simple tool to split a bill with your friends.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
